__BASE__: null
MERGE_DEFAULT: false

DATASET:
  NAME: "deepeyenet"
  DATASET_PATH: "datasets/deepeyenet"
  CONVERTED_DATASET_PATH: "datasets/deepeyenet/converted"

MODEL:
  ARCHITECTURE: "ViT-B-16"
  PRETRAINED_WEIGHTS: "openai"

TRAINING:
  BATCH_SIZE_PER_GPU: 2048
  EPOCHS: 50
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.2
  WORKERS: 10
  PRECISION: "amp"
  WARMUP_EPOCHS: 5
  ADAM_BETA1: 0.9
  ADAM_BETA2: 0.98
  GRADIENT_ACCUMULATION_STEPS: 1
  NUM_DEVICES: 1
  USE_WEBDATASET: false

RESUME: false
GRADIENT_CHECKPOINTING: true

OUTPUT:
  SAVE_DIR: "clip_models_106080954"
  LOG_INTERVAL: 7
  WANDB_PROJECT_BASE_NAME: "pmo-experiments"
  RUN_NAME: null

SEED: 106080954
